    drop table attempt if exists;

    drop table game if exists;

    drop table syllabus if exists;

    create table attempt (
        id integer generated by default as identity (start with 1),
        isGuessed boolean,
        letter varchar(1),
        game_id integer,
        primary key (id)
    );

    create table syllabus (
        id integer generated by default as identity (start with 1),
        phrase varchar(255),
        primary key (id)
    );

    create table game (
        id integer generated by default as identity (start with 1),
        gameStatus varchar(255),
        maxAttempts tinyint default 6,
        syllabus_id integer,
        primary key (id)
    );
    ALTER TABLE game ALTER COLUMN maxAttempts SET DEFAULT 6;

